//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace WssSVLib.People {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://schemas.microsoft.com/sharepoint/soap/", ItemName="string")]
    public class ArrayOfString : System.Collections.ObjectModel.ObservableCollection<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="SPPrincipalType", Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public enum SPPrincipalType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DistributionList = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecurityGroup = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SharePointGroup = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 32,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrincipalInfo", Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class PrincipalInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AccountNameField;
        
        private int UserInfoIDField;
        
        private string DisplayNameField;
        
        private string EmailField;
        
        private string DepartmentField;
        
        private string TitleField;
        
        private bool IsResolvedField;
        
        private System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> MoreMatchesField;
        
        private WssSVLib.People.SPPrincipalType PrincipalTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserInfoID {
            get {
                return this.UserInfoIDField;
            }
            set {
                if ((this.UserInfoIDField.Equals(value) != true)) {
                    this.UserInfoIDField = value;
                    this.RaisePropertyChanged("UserInfoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsResolved {
            get {
                return this.IsResolvedField;
            }
            set {
                if ((this.IsResolvedField.Equals(value) != true)) {
                    this.IsResolvedField = value;
                    this.RaisePropertyChanged("IsResolved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> MoreMatches {
            get {
                return this.MoreMatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.MoreMatchesField, value) != true)) {
                    this.MoreMatchesField = value;
                    this.RaisePropertyChanged("MoreMatches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public WssSVLib.People.SPPrincipalType PrincipalType {
            get {
                return this.PrincipalTypeField;
            }
            set {
                if ((this.PrincipalTypeField.Equals(value) != true)) {
                    this.PrincipalTypeField = value;
                    this.RaisePropertyChanged("PrincipalType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName="People.PeopleSoap")]
    public interface PeopleSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://schemas.microsoft.com/sharepoint/soap/ResolvePrincipals", ReplyAction="*")]
        System.IAsyncResult BeginResolvePrincipals(WssSVLib.People.ResolvePrincipalsRequest request, System.AsyncCallback callback, object asyncState);
        
        WssSVLib.People.ResolvePrincipalsResponse EndResolvePrincipals(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://schemas.microsoft.com/sharepoint/soap/SearchPrincipals", ReplyAction="*")]
        System.IAsyncResult BeginSearchPrincipals(WssSVLib.People.SearchPrincipalsRequest request, System.AsyncCallback callback, object asyncState);
        
        WssSVLib.People.SearchPrincipalsResponse EndSearchPrincipals(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResolvePrincipalsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResolvePrincipals", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public WssSVLib.People.ResolvePrincipalsRequestBody Body;
        
        public ResolvePrincipalsRequest() {
        }
        
        public ResolvePrincipalsRequest(WssSVLib.People.ResolvePrincipalsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class ResolvePrincipalsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WssSVLib.People.ArrayOfString principalKeys;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public WssSVLib.People.SPPrincipalType principalType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool addToUserInfoList;
        
        public ResolvePrincipalsRequestBody() {
        }
        
        public ResolvePrincipalsRequestBody(WssSVLib.People.ArrayOfString principalKeys, WssSVLib.People.SPPrincipalType principalType, bool addToUserInfoList) {
            this.principalKeys = principalKeys;
            this.principalType = principalType;
            this.addToUserInfoList = addToUserInfoList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResolvePrincipalsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResolvePrincipalsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public WssSVLib.People.ResolvePrincipalsResponseBody Body;
        
        public ResolvePrincipalsResponse() {
        }
        
        public ResolvePrincipalsResponse(WssSVLib.People.ResolvePrincipalsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class ResolvePrincipalsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> ResolvePrincipalsResult;
        
        public ResolvePrincipalsResponseBody() {
        }
        
        public ResolvePrincipalsResponseBody(System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> ResolvePrincipalsResult) {
            this.ResolvePrincipalsResult = ResolvePrincipalsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchPrincipalsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchPrincipals", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public WssSVLib.People.SearchPrincipalsRequestBody Body;
        
        public SearchPrincipalsRequest() {
        }
        
        public SearchPrincipalsRequest(WssSVLib.People.SearchPrincipalsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class SearchPrincipalsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchText;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int maxResults;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public WssSVLib.People.SPPrincipalType principalType;
        
        public SearchPrincipalsRequestBody() {
        }
        
        public SearchPrincipalsRequestBody(string searchText, int maxResults, WssSVLib.People.SPPrincipalType principalType) {
            this.searchText = searchText;
            this.maxResults = maxResults;
            this.principalType = principalType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchPrincipalsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchPrincipalsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public WssSVLib.People.SearchPrincipalsResponseBody Body;
        
        public SearchPrincipalsResponse() {
        }
        
        public SearchPrincipalsResponse(WssSVLib.People.SearchPrincipalsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class SearchPrincipalsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> SearchPrincipalsResult;
        
        public SearchPrincipalsResponseBody() {
        }
        
        public SearchPrincipalsResponseBody(System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> SearchPrincipalsResult) {
            this.SearchPrincipalsResult = SearchPrincipalsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PeopleSoapChannel : WssSVLib.People.PeopleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ResolvePrincipalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ResolvePrincipalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SearchPrincipalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchPrincipalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PeopleSoapClient : System.ServiceModel.ClientBase<WssSVLib.People.PeopleSoap>, WssSVLib.People.PeopleSoap {
        
        private BeginOperationDelegate onBeginResolvePrincipalsDelegate;
        
        private EndOperationDelegate onEndResolvePrincipalsDelegate;
        
        private System.Threading.SendOrPostCallback onResolvePrincipalsCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchPrincipalsDelegate;
        
        private EndOperationDelegate onEndSearchPrincipalsDelegate;
        
        private System.Threading.SendOrPostCallback onSearchPrincipalsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PeopleSoapClient() {
        }
        
        public PeopleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeopleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ResolvePrincipalsCompletedEventArgs> ResolvePrincipalsCompleted;
        
        public event System.EventHandler<SearchPrincipalsCompletedEventArgs> SearchPrincipalsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WssSVLib.People.PeopleSoap.BeginResolvePrincipals(WssSVLib.People.ResolvePrincipalsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginResolvePrincipals(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginResolvePrincipals(WssSVLib.People.ArrayOfString principalKeys, WssSVLib.People.SPPrincipalType principalType, bool addToUserInfoList, System.AsyncCallback callback, object asyncState) {
            WssSVLib.People.ResolvePrincipalsRequest inValue = new WssSVLib.People.ResolvePrincipalsRequest();
            inValue.Body = new WssSVLib.People.ResolvePrincipalsRequestBody();
            inValue.Body.principalKeys = principalKeys;
            inValue.Body.principalType = principalType;
            inValue.Body.addToUserInfoList = addToUserInfoList;
            return ((WssSVLib.People.PeopleSoap)(this)).BeginResolvePrincipals(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WssSVLib.People.ResolvePrincipalsResponse WssSVLib.People.PeopleSoap.EndResolvePrincipals(System.IAsyncResult result) {
            return base.Channel.EndResolvePrincipals(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> EndResolvePrincipals(System.IAsyncResult result) {
            WssSVLib.People.ResolvePrincipalsResponse retVal = ((WssSVLib.People.PeopleSoap)(this)).EndResolvePrincipals(result);
            return retVal.Body.ResolvePrincipalsResult;
        }
        
        private System.IAsyncResult OnBeginResolvePrincipals(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WssSVLib.People.ArrayOfString principalKeys = ((WssSVLib.People.ArrayOfString)(inValues[0]));
            WssSVLib.People.SPPrincipalType principalType = ((WssSVLib.People.SPPrincipalType)(inValues[1]));
            bool addToUserInfoList = ((bool)(inValues[2]));
            return this.BeginResolvePrincipals(principalKeys, principalType, addToUserInfoList, callback, asyncState);
        }
        
        private object[] OnEndResolvePrincipals(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> retVal = this.EndResolvePrincipals(result);
            return new object[] {
                    retVal};
        }
        
        private void OnResolvePrincipalsCompleted(object state) {
            if ((this.ResolvePrincipalsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ResolvePrincipalsCompleted(this, new ResolvePrincipalsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ResolvePrincipalsAsync(WssSVLib.People.ArrayOfString principalKeys, WssSVLib.People.SPPrincipalType principalType, bool addToUserInfoList) {
            this.ResolvePrincipalsAsync(principalKeys, principalType, addToUserInfoList, null);
        }
        
        public void ResolvePrincipalsAsync(WssSVLib.People.ArrayOfString principalKeys, WssSVLib.People.SPPrincipalType principalType, bool addToUserInfoList, object userState) {
            if ((this.onBeginResolvePrincipalsDelegate == null)) {
                this.onBeginResolvePrincipalsDelegate = new BeginOperationDelegate(this.OnBeginResolvePrincipals);
            }
            if ((this.onEndResolvePrincipalsDelegate == null)) {
                this.onEndResolvePrincipalsDelegate = new EndOperationDelegate(this.OnEndResolvePrincipals);
            }
            if ((this.onResolvePrincipalsCompletedDelegate == null)) {
                this.onResolvePrincipalsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnResolvePrincipalsCompleted);
            }
            base.InvokeAsync(this.onBeginResolvePrincipalsDelegate, new object[] {
                        principalKeys,
                        principalType,
                        addToUserInfoList}, this.onEndResolvePrincipalsDelegate, this.onResolvePrincipalsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WssSVLib.People.PeopleSoap.BeginSearchPrincipals(WssSVLib.People.SearchPrincipalsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchPrincipals(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSearchPrincipals(string searchText, int maxResults, WssSVLib.People.SPPrincipalType principalType, System.AsyncCallback callback, object asyncState) {
            WssSVLib.People.SearchPrincipalsRequest inValue = new WssSVLib.People.SearchPrincipalsRequest();
            inValue.Body = new WssSVLib.People.SearchPrincipalsRequestBody();
            inValue.Body.searchText = searchText;
            inValue.Body.maxResults = maxResults;
            inValue.Body.principalType = principalType;
            return ((WssSVLib.People.PeopleSoap)(this)).BeginSearchPrincipals(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WssSVLib.People.SearchPrincipalsResponse WssSVLib.People.PeopleSoap.EndSearchPrincipals(System.IAsyncResult result) {
            return base.Channel.EndSearchPrincipals(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> EndSearchPrincipals(System.IAsyncResult result) {
            WssSVLib.People.SearchPrincipalsResponse retVal = ((WssSVLib.People.PeopleSoap)(this)).EndSearchPrincipals(result);
            return retVal.Body.SearchPrincipalsResult;
        }
        
        private System.IAsyncResult OnBeginSearchPrincipals(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string searchText = ((string)(inValues[0]));
            int maxResults = ((int)(inValues[1]));
            WssSVLib.People.SPPrincipalType principalType = ((WssSVLib.People.SPPrincipalType)(inValues[2]));
            return this.BeginSearchPrincipals(searchText, maxResults, principalType, callback, asyncState);
        }
        
        private object[] OnEndSearchPrincipals(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WssSVLib.People.PrincipalInfo> retVal = this.EndSearchPrincipals(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchPrincipalsCompleted(object state) {
            if ((this.SearchPrincipalsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchPrincipalsCompleted(this, new SearchPrincipalsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchPrincipalsAsync(string searchText, int maxResults, WssSVLib.People.SPPrincipalType principalType) {
            this.SearchPrincipalsAsync(searchText, maxResults, principalType, null);
        }
        
        public void SearchPrincipalsAsync(string searchText, int maxResults, WssSVLib.People.SPPrincipalType principalType, object userState) {
            if ((this.onBeginSearchPrincipalsDelegate == null)) {
                this.onBeginSearchPrincipalsDelegate = new BeginOperationDelegate(this.OnBeginSearchPrincipals);
            }
            if ((this.onEndSearchPrincipalsDelegate == null)) {
                this.onEndSearchPrincipalsDelegate = new EndOperationDelegate(this.OnEndSearchPrincipals);
            }
            if ((this.onSearchPrincipalsCompletedDelegate == null)) {
                this.onSearchPrincipalsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchPrincipalsCompleted);
            }
            base.InvokeAsync(this.onBeginSearchPrincipalsDelegate, new object[] {
                        searchText,
                        maxResults,
                        principalType}, this.onEndSearchPrincipalsDelegate, this.onSearchPrincipalsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WssSVLib.People.PeopleSoap CreateChannel() {
            return new PeopleSoapClientChannel(this);
        }
        
        private class PeopleSoapClientChannel : ChannelBase<WssSVLib.People.PeopleSoap>, WssSVLib.People.PeopleSoap {
            
            public PeopleSoapClientChannel(System.ServiceModel.ClientBase<WssSVLib.People.PeopleSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginResolvePrincipals(WssSVLib.People.ResolvePrincipalsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ResolvePrincipals", _args, callback, asyncState);
                return _result;
            }
            
            public WssSVLib.People.ResolvePrincipalsResponse EndResolvePrincipals(System.IAsyncResult result) {
                object[] _args = new object[0];
                WssSVLib.People.ResolvePrincipalsResponse _result = ((WssSVLib.People.ResolvePrincipalsResponse)(base.EndInvoke("ResolvePrincipals", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSearchPrincipals(WssSVLib.People.SearchPrincipalsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SearchPrincipals", _args, callback, asyncState);
                return _result;
            }
            
            public WssSVLib.People.SearchPrincipalsResponse EndSearchPrincipals(System.IAsyncResult result) {
                object[] _args = new object[0];
                WssSVLib.People.SearchPrincipalsResponse _result = ((WssSVLib.People.SearchPrincipalsResponse)(base.EndInvoke("SearchPrincipals", _args, result)));
                return _result;
            }
        }
    }
}
