//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace WssSVLib.Forms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName="Forms.FormsSoap")]
    public interface FormsSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://schemas.microsoft.com/sharepoint/soap/GetFormCollection", ReplyAction="*")]
        System.IAsyncResult BeginGetFormCollection(WssSVLib.Forms.GetFormCollectionRequest request, System.AsyncCallback callback, object asyncState);
        
        WssSVLib.Forms.GetFormCollectionResponse EndGetFormCollection(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://schemas.microsoft.com/sharepoint/soap/GetForm", ReplyAction="*")]
        System.IAsyncResult BeginGetForm(WssSVLib.Forms.GetFormRequest request, System.AsyncCallback callback, object asyncState);
        
        WssSVLib.Forms.GetFormResponse EndGetForm(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFormCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFormCollection", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public WssSVLib.Forms.GetFormCollectionRequestBody Body;
        
        public GetFormCollectionRequest() {
        }
        
        public GetFormCollectionRequest(WssSVLib.Forms.GetFormCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetFormCollectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        public GetFormCollectionRequestBody() {
        }
        
        public GetFormCollectionRequestBody(string listName) {
            this.listName = listName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFormCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFormCollectionResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public WssSVLib.Forms.GetFormCollectionResponseBody Body;
        
        public GetFormCollectionResponse() {
        }
        
        public GetFormCollectionResponse(WssSVLib.Forms.GetFormCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetFormCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFormCollectionResult;
        
        public GetFormCollectionResponseBody() {
        }
        
        public GetFormCollectionResponseBody(System.Xml.Linq.XElement GetFormCollectionResult) {
            this.GetFormCollectionResult = GetFormCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFormRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetForm", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public WssSVLib.Forms.GetFormRequestBody Body;
        
        public GetFormRequest() {
        }
        
        public GetFormRequest(WssSVLib.Forms.GetFormRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetFormRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string formUrl;
        
        public GetFormRequestBody() {
        }
        
        public GetFormRequestBody(string listName, string formUrl) {
            this.listName = listName;
            this.formUrl = formUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFormResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFormResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/", Order=0)]
        public WssSVLib.Forms.GetFormResponseBody Body;
        
        public GetFormResponse() {
        }
        
        public GetFormResponse(WssSVLib.Forms.GetFormResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/")]
    public partial class GetFormResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetFormResult;
        
        public GetFormResponseBody() {
        }
        
        public GetFormResponseBody(System.Xml.Linq.XElement GetFormResult) {
            this.GetFormResult = GetFormResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface FormsSoapChannel : WssSVLib.Forms.FormsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetFormCollectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFormCollectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Xml.Linq.XElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Xml.Linq.XElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Xml.Linq.XElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Xml.Linq.XElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class FormsSoapClient : System.ServiceModel.ClientBase<WssSVLib.Forms.FormsSoap>, WssSVLib.Forms.FormsSoap {
        
        private BeginOperationDelegate onBeginGetFormCollectionDelegate;
        
        private EndOperationDelegate onEndGetFormCollectionDelegate;
        
        private System.Threading.SendOrPostCallback onGetFormCollectionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFormDelegate;
        
        private EndOperationDelegate onEndGetFormDelegate;
        
        private System.Threading.SendOrPostCallback onGetFormCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public FormsSoapClient() {
        }
        
        public FormsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetFormCollectionCompletedEventArgs> GetFormCollectionCompleted;
        
        public event System.EventHandler<GetFormCompletedEventArgs> GetFormCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WssSVLib.Forms.FormsSoap.BeginGetFormCollection(WssSVLib.Forms.GetFormCollectionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFormCollection(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetFormCollection(string listName, System.AsyncCallback callback, object asyncState) {
            WssSVLib.Forms.GetFormCollectionRequest inValue = new WssSVLib.Forms.GetFormCollectionRequest();
            inValue.Body = new WssSVLib.Forms.GetFormCollectionRequestBody();
            inValue.Body.listName = listName;
            return ((WssSVLib.Forms.FormsSoap)(this)).BeginGetFormCollection(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WssSVLib.Forms.GetFormCollectionResponse WssSVLib.Forms.FormsSoap.EndGetFormCollection(System.IAsyncResult result) {
            return base.Channel.EndGetFormCollection(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Xml.Linq.XElement EndGetFormCollection(System.IAsyncResult result) {
            WssSVLib.Forms.GetFormCollectionResponse retVal = ((WssSVLib.Forms.FormsSoap)(this)).EndGetFormCollection(result);
            return retVal.Body.GetFormCollectionResult;
        }
        
        private System.IAsyncResult OnBeginGetFormCollection(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string listName = ((string)(inValues[0]));
            return this.BeginGetFormCollection(listName, callback, asyncState);
        }
        
        private object[] OnEndGetFormCollection(System.IAsyncResult result) {
            System.Xml.Linq.XElement retVal = this.EndGetFormCollection(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFormCollectionCompleted(object state) {
            if ((this.GetFormCollectionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFormCollectionCompleted(this, new GetFormCollectionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFormCollectionAsync(string listName) {
            this.GetFormCollectionAsync(listName, null);
        }
        
        public void GetFormCollectionAsync(string listName, object userState) {
            if ((this.onBeginGetFormCollectionDelegate == null)) {
                this.onBeginGetFormCollectionDelegate = new BeginOperationDelegate(this.OnBeginGetFormCollection);
            }
            if ((this.onEndGetFormCollectionDelegate == null)) {
                this.onEndGetFormCollectionDelegate = new EndOperationDelegate(this.OnEndGetFormCollection);
            }
            if ((this.onGetFormCollectionCompletedDelegate == null)) {
                this.onGetFormCollectionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFormCollectionCompleted);
            }
            base.InvokeAsync(this.onBeginGetFormCollectionDelegate, new object[] {
                        listName}, this.onEndGetFormCollectionDelegate, this.onGetFormCollectionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WssSVLib.Forms.FormsSoap.BeginGetForm(WssSVLib.Forms.GetFormRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetForm(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetForm(string listName, string formUrl, System.AsyncCallback callback, object asyncState) {
            WssSVLib.Forms.GetFormRequest inValue = new WssSVLib.Forms.GetFormRequest();
            inValue.Body = new WssSVLib.Forms.GetFormRequestBody();
            inValue.Body.listName = listName;
            inValue.Body.formUrl = formUrl;
            return ((WssSVLib.Forms.FormsSoap)(this)).BeginGetForm(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WssSVLib.Forms.GetFormResponse WssSVLib.Forms.FormsSoap.EndGetForm(System.IAsyncResult result) {
            return base.Channel.EndGetForm(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Xml.Linq.XElement EndGetForm(System.IAsyncResult result) {
            WssSVLib.Forms.GetFormResponse retVal = ((WssSVLib.Forms.FormsSoap)(this)).EndGetForm(result);
            return retVal.Body.GetFormResult;
        }
        
        private System.IAsyncResult OnBeginGetForm(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string listName = ((string)(inValues[0]));
            string formUrl = ((string)(inValues[1]));
            return this.BeginGetForm(listName, formUrl, callback, asyncState);
        }
        
        private object[] OnEndGetForm(System.IAsyncResult result) {
            System.Xml.Linq.XElement retVal = this.EndGetForm(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFormCompleted(object state) {
            if ((this.GetFormCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFormCompleted(this, new GetFormCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFormAsync(string listName, string formUrl) {
            this.GetFormAsync(listName, formUrl, null);
        }
        
        public void GetFormAsync(string listName, string formUrl, object userState) {
            if ((this.onBeginGetFormDelegate == null)) {
                this.onBeginGetFormDelegate = new BeginOperationDelegate(this.OnBeginGetForm);
            }
            if ((this.onEndGetFormDelegate == null)) {
                this.onEndGetFormDelegate = new EndOperationDelegate(this.OnEndGetForm);
            }
            if ((this.onGetFormCompletedDelegate == null)) {
                this.onGetFormCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFormCompleted);
            }
            base.InvokeAsync(this.onBeginGetFormDelegate, new object[] {
                        listName,
                        formUrl}, this.onEndGetFormDelegate, this.onGetFormCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WssSVLib.Forms.FormsSoap CreateChannel() {
            return new FormsSoapClientChannel(this);
        }
        
        private class FormsSoapClientChannel : ChannelBase<WssSVLib.Forms.FormsSoap>, WssSVLib.Forms.FormsSoap {
            
            public FormsSoapClientChannel(System.ServiceModel.ClientBase<WssSVLib.Forms.FormsSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetFormCollection(WssSVLib.Forms.GetFormCollectionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetFormCollection", _args, callback, asyncState);
                return _result;
            }
            
            public WssSVLib.Forms.GetFormCollectionResponse EndGetFormCollection(System.IAsyncResult result) {
                object[] _args = new object[0];
                WssSVLib.Forms.GetFormCollectionResponse _result = ((WssSVLib.Forms.GetFormCollectionResponse)(base.EndInvoke("GetFormCollection", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetForm(WssSVLib.Forms.GetFormRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetForm", _args, callback, asyncState);
                return _result;
            }
            
            public WssSVLib.Forms.GetFormResponse EndGetForm(System.IAsyncResult result) {
                object[] _args = new object[0];
                WssSVLib.Forms.GetFormResponse _result = ((WssSVLib.Forms.GetFormResponse)(base.EndInvoke("GetForm", _args, result)));
                return _result;
            }
        }
    }
}
