<?xml version="1.0" encoding="utf-8"?>
<Database Name="kjpt_cme" Class="KjptDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HASEE\SQLEXPRESS;Initial Catalog=kjpt_cme;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="kjpt_cmeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.com_dept" Member="com_depts">
    <Type Name="com_dept">
      <Column Name="dept_id" Type="System.String" DbType="Char(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dept_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Passwd" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="unit_id" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="parent_id" Type="System.String" DbType="Char(9) NOT NULL" CanBeNull="false" />
      <Column Name="kj_dept_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="list_order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="add_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.com_person" Member="com_persons">
    <Type Name="com_person">
      <Column Name="com_person_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="person_no" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Other_no" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="person_name" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="sex" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="cert_id" Type="System.String" DbType="VarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nation" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="party" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="university" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mobile" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="spec" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="job_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="education" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="degree" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="prof_cert_id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hospital_duty" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="photo" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="person_type" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="passwd" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Dept_id" Type="System.String" DbType="Char(9) NOT NULL" CanBeNull="false" />
      <Column Name="Update_other_no" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Transfer_state" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="add_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BatchGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="is_create_card" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_charges" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="internals" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="update_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.com_unit" Member="com_units">
    <Type Name="com_unit">
      <Column Name="unit_id" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="unit_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gov_passwd" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="short_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="contact" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="postcode" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="parent_unit" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="hospital_level" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="cme_score_check_mode" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="cme_standard_kind_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Proj_control_top_unit" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="attendance_grantscore_top_unit" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="cme_score_avail_state" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="cme_score_check_state" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="tmp_oper_people_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="photo_address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="privilege" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="list_order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="open_dept" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="add_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.cme_person" Member="cme_persons">
    <Type Name="cme_person">
      <Column Name="cme_person_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="com_person_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="cme_year" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="title_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="person_state_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="unit" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="hospital_level" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="add_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="key_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.cme_year" Member="cme_years">
    <Type Name="cme_year">
      <Column Name="cme_year_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cme_standard_kind_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="cme_year" Member="cme_year1" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="start_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="add_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.cme_unit_level" Member="cme_unit_levels">
    <Type Name="cme_unit_level">
      <Column Name="unit_level_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="unit_level_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cme_standard_kind_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="list_order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="add_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>