#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf01
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="kjpt_cme")]
	public partial class KjptDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcom_dept(com_dept instance);
    partial void Updatecom_dept(com_dept instance);
    partial void Deletecom_dept(com_dept instance);
    partial void Insertcom_person(com_person instance);
    partial void Updatecom_person(com_person instance);
    partial void Deletecom_person(com_person instance);
    partial void Insertcom_unit(com_unit instance);
    partial void Updatecom_unit(com_unit instance);
    partial void Deletecom_unit(com_unit instance);
    partial void Insertcme_person(cme_person instance);
    partial void Updatecme_person(cme_person instance);
    partial void Deletecme_person(cme_person instance);
    partial void Insertcme_year(cme_year instance);
    partial void Updatecme_year(cme_year instance);
    partial void Deletecme_year(cme_year instance);
    partial void Insertcme_unit_level(cme_unit_level instance);
    partial void Updatecme_unit_level(cme_unit_level instance);
    partial void Deletecme_unit_level(cme_unit_level instance);
    #endregion
		
		public KjptDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["kjpt_cmeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KjptDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KjptDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KjptDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KjptDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<com_dept> com_depts
		{
			get
			{
				return this.GetTable<com_dept>();
			}
		}
		
		public System.Data.Linq.Table<com_person> com_persons
		{
			get
			{
				return this.GetTable<com_person>();
			}
		}
		
		public System.Data.Linq.Table<com_unit> com_units
		{
			get
			{
				return this.GetTable<com_unit>();
			}
		}
		
		public System.Data.Linq.Table<cme_person> cme_persons
		{
			get
			{
				return this.GetTable<cme_person>();
			}
		}
		
		public System.Data.Linq.Table<cme_year> cme_years
		{
			get
			{
				return this.GetTable<cme_year>();
			}
		}
		
		public System.Data.Linq.Table<cme_unit_level> cme_unit_levels
		{
			get
			{
				return this.GetTable<cme_unit_level>();
			}
		}
	}

    [Table(Name = "kjpt_common.dbo.com_dept")]
	public partial class com_dept : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _dept_id;
		
		private string _dept_name;
		
		private string _Passwd;
		
		private string _unit_id;
		
		private string _parent_id;
		
		private string _kj_dept_id;
		
		private int _list_order;
		
		private System.DateTime _add_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondept_idChanging(string value);
    partial void Ondept_idChanged();
    partial void Ondept_nameChanging(string value);
    partial void Ondept_nameChanged();
    partial void OnPasswdChanging(string value);
    partial void OnPasswdChanged();
    partial void Onunit_idChanging(string value);
    partial void Onunit_idChanged();
    partial void Onparent_idChanging(string value);
    partial void Onparent_idChanged();
    partial void Onkj_dept_idChanging(string value);
    partial void Onkj_dept_idChanged();
    partial void Onlist_orderChanging(int value);
    partial void Onlist_orderChanged();
    partial void Onadd_timeChanging(System.DateTime value);
    partial void Onadd_timeChanged();
    #endregion
		
		public com_dept()
		{
			OnCreated();
		}
		
		[Column(Storage="_dept_id", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string dept_id
		{
			get
			{
				return this._dept_id;
			}
			set
			{
				if ((this._dept_id != value))
				{
					this.Ondept_idChanging(value);
					this.SendPropertyChanging();
					this._dept_id = value;
					this.SendPropertyChanged("dept_id");
					this.Ondept_idChanged();
				}
			}
		}
		
		[Column(Storage="_dept_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string dept_name
		{
			get
			{
				return this._dept_name;
			}
			set
			{
				if ((this._dept_name != value))
				{
					this.Ondept_nameChanging(value);
					this.SendPropertyChanging();
					this._dept_name = value;
					this.SendPropertyChanged("dept_name");
					this.Ondept_nameChanged();
				}
			}
		}
		
		[Column(Storage="_Passwd", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Passwd
		{
			get
			{
				return this._Passwd;
			}
			set
			{
				if ((this._Passwd != value))
				{
					this.OnPasswdChanging(value);
					this.SendPropertyChanging();
					this._Passwd = value;
					this.SendPropertyChanged("Passwd");
					this.OnPasswdChanged();
				}
			}
		}
		
		[Column(Storage="_unit_id", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string unit_id
		{
			get
			{
				return this._unit_id;
			}
			set
			{
				if ((this._unit_id != value))
				{
					this.Onunit_idChanging(value);
					this.SendPropertyChanging();
					this._unit_id = value;
					this.SendPropertyChanged("unit_id");
					this.Onunit_idChanged();
				}
			}
		}
		
		[Column(Storage="_parent_id", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this.Onparent_idChanging(value);
					this.SendPropertyChanging();
					this._parent_id = value;
					this.SendPropertyChanged("parent_id");
					this.Onparent_idChanged();
				}
			}
		}
		
		[Column(Storage="_kj_dept_id", DbType="VarChar(50)")]
		public string kj_dept_id
		{
			get
			{
				return this._kj_dept_id;
			}
			set
			{
				if ((this._kj_dept_id != value))
				{
					this.Onkj_dept_idChanging(value);
					this.SendPropertyChanging();
					this._kj_dept_id = value;
					this.SendPropertyChanged("kj_dept_id");
					this.Onkj_dept_idChanged();
				}
			}
		}
		
		[Column(Storage="_list_order", DbType="Int NOT NULL")]
		public int list_order
		{
			get
			{
				return this._list_order;
			}
			set
			{
				if ((this._list_order != value))
				{
					this.Onlist_orderChanging(value);
					this.SendPropertyChanging();
					this._list_order = value;
					this.SendPropertyChanged("list_order");
					this.Onlist_orderChanged();
				}
			}
		}
		
		[Column(Storage="_add_time", DbType="DateTime NOT NULL")]
		public System.DateTime add_time
		{
			get
			{
				return this._add_time;
			}
			set
			{
				if ((this._add_time != value))
				{
					this.Onadd_timeChanging(value);
					this.SendPropertyChanging();
					this._add_time = value;
					this.SendPropertyChanged("add_time");
					this.Onadd_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

    [Table(Name = "kjpt_common.dbo.com_person")]
	public partial class com_person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _com_person_id;
		
		private string _person_no;
		
		private string _Other_no;
		
		private string _person_name;
		
		private string _sex;
		
		private string _cert_id;
		
		private System.DateTime _birthday;
		
		private System.Nullable<System.Guid> _nation;
		
		private System.Nullable<System.Guid> _party;
		
		private string _university;
		
		private string _telephone;
		
		private string _mobile;
		
		private string _email;
		
		private System.Nullable<System.Guid> _spec;
		
		private System.DateTime _job_date;
		
		private System.Nullable<System.Guid> _education;
		
		private System.Nullable<System.Guid> _degree;
		
		private string _prof_cert_id;
		
		private System.Nullable<System.Guid> _hospital_duty;
		
		private string _photo;
		
		private System.Nullable<System.Guid> _person_type;
		
		private string _remark;
		
		private string _passwd;
		
		private string _Dept_id;
		
		private byte _Update_other_no;
		
		private int _Transfer_state;
		
		private System.DateTime _add_time;
		
		private System.Nullable<System.Guid> _BatchGuid;
		
		private System.Nullable<bool> _is_create_card;
		
		private System.Nullable<bool> _is_charges;
		
		private string _internals;
		
		private System.DateTime _update_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncom_person_idChanging(System.Guid value);
    partial void Oncom_person_idChanged();
    partial void Onperson_noChanging(string value);
    partial void Onperson_noChanged();
    partial void OnOther_noChanging(string value);
    partial void OnOther_noChanged();
    partial void Onperson_nameChanging(string value);
    partial void Onperson_nameChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void Oncert_idChanging(string value);
    partial void Oncert_idChanged();
    partial void OnbirthdayChanging(System.DateTime value);
    partial void OnbirthdayChanged();
    partial void OnnationChanging(System.Nullable<System.Guid> value);
    partial void OnnationChanged();
    partial void OnpartyChanging(System.Nullable<System.Guid> value);
    partial void OnpartyChanged();
    partial void OnuniversityChanging(string value);
    partial void OnuniversityChanged();
    partial void OntelephoneChanging(string value);
    partial void OntelephoneChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnspecChanging(System.Nullable<System.Guid> value);
    partial void OnspecChanged();
    partial void Onjob_dateChanging(System.DateTime value);
    partial void Onjob_dateChanged();
    partial void OneducationChanging(System.Nullable<System.Guid> value);
    partial void OneducationChanged();
    partial void OndegreeChanging(System.Nullable<System.Guid> value);
    partial void OndegreeChanged();
    partial void Onprof_cert_idChanging(string value);
    partial void Onprof_cert_idChanged();
    partial void Onhospital_dutyChanging(System.Nullable<System.Guid> value);
    partial void Onhospital_dutyChanged();
    partial void OnphotoChanging(string value);
    partial void OnphotoChanged();
    partial void Onperson_typeChanging(System.Nullable<System.Guid> value);
    partial void Onperson_typeChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OnpasswdChanging(string value);
    partial void OnpasswdChanged();
    partial void OnDept_idChanging(string value);
    partial void OnDept_idChanged();
    partial void OnUpdate_other_noChanging(byte value);
    partial void OnUpdate_other_noChanged();
    partial void OnTransfer_stateChanging(int value);
    partial void OnTransfer_stateChanged();
    partial void Onadd_timeChanging(System.DateTime value);
    partial void Onadd_timeChanged();
    partial void OnBatchGuidChanging(System.Nullable<System.Guid> value);
    partial void OnBatchGuidChanged();
    partial void Onis_create_cardChanging(System.Nullable<bool> value);
    partial void Onis_create_cardChanged();
    partial void Onis_chargesChanging(System.Nullable<bool> value);
    partial void Onis_chargesChanged();
    partial void OninternalsChanging(string value);
    partial void OninternalsChanged();
    partial void Onupdate_timeChanging(System.DateTime value);
    partial void Onupdate_timeChanged();
    #endregion
		
		public com_person()
		{
			OnCreated();
		}
		
		[Column(Storage="_com_person_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid com_person_id
		{
			get
			{
				return this._com_person_id;
			}
			set
			{
				if ((this._com_person_id != value))
				{
					this.Oncom_person_idChanging(value);
					this.SendPropertyChanging();
					this._com_person_id = value;
					this.SendPropertyChanged("com_person_id");
					this.Oncom_person_idChanged();
				}
			}
		}
		
		[Column(Storage="_person_no", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string person_no
		{
			get
			{
				return this._person_no;
			}
			set
			{
				if ((this._person_no != value))
				{
					this.Onperson_noChanging(value);
					this.SendPropertyChanging();
					this._person_no = value;
					this.SendPropertyChanged("person_no");
					this.Onperson_noChanged();
				}
			}
		}
		
		[Column(Storage="_Other_no", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Other_no
		{
			get
			{
				return this._Other_no;
			}
			set
			{
				if ((this._Other_no != value))
				{
					this.OnOther_noChanging(value);
					this.SendPropertyChanging();
					this._Other_no = value;
					this.SendPropertyChanged("Other_no");
					this.OnOther_noChanged();
				}
			}
		}
		
		[Column(Storage="_person_name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string person_name
		{
			get
			{
				return this._person_name;
			}
			set
			{
				if ((this._person_name != value))
				{
					this.Onperson_nameChanging(value);
					this.SendPropertyChanging();
					this._person_name = value;
					this.SendPropertyChanged("person_name");
					this.Onperson_nameChanged();
				}
			}
		}
		
		[Column(Storage="_sex", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[Column(Storage="_cert_id", DbType="VarChar(18) NOT NULL", CanBeNull=false)]
		public string cert_id
		{
			get
			{
				return this._cert_id;
			}
			set
			{
				if ((this._cert_id != value))
				{
					this.Oncert_idChanging(value);
					this.SendPropertyChanging();
					this._cert_id = value;
					this.SendPropertyChanged("cert_id");
					this.Oncert_idChanged();
				}
			}
		}
		
		[Column(Storage="_birthday", DbType="DateTime NOT NULL")]
		public System.DateTime birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[Column(Storage="_nation", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> nation
		{
			get
			{
				return this._nation;
			}
			set
			{
				if ((this._nation != value))
				{
					this.OnnationChanging(value);
					this.SendPropertyChanging();
					this._nation = value;
					this.SendPropertyChanged("nation");
					this.OnnationChanged();
				}
			}
		}
		
		[Column(Storage="_party", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> party
		{
			get
			{
				return this._party;
			}
			set
			{
				if ((this._party != value))
				{
					this.OnpartyChanging(value);
					this.SendPropertyChanging();
					this._party = value;
					this.SendPropertyChanged("party");
					this.OnpartyChanged();
				}
			}
		}
		
		[Column(Storage="_university", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string university
		{
			get
			{
				return this._university;
			}
			set
			{
				if ((this._university != value))
				{
					this.OnuniversityChanging(value);
					this.SendPropertyChanging();
					this._university = value;
					this.SendPropertyChanged("university");
					this.OnuniversityChanged();
				}
			}
		}
		
		[Column(Storage="_telephone", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this.OntelephoneChanging(value);
					this.SendPropertyChanging();
					this._telephone = value;
					this.SendPropertyChanged("telephone");
					this.OntelephoneChanged();
				}
			}
		}
		
		[Column(Storage="_mobile", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_spec", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> spec
		{
			get
			{
				return this._spec;
			}
			set
			{
				if ((this._spec != value))
				{
					this.OnspecChanging(value);
					this.SendPropertyChanging();
					this._spec = value;
					this.SendPropertyChanged("spec");
					this.OnspecChanged();
				}
			}
		}
		
		[Column(Storage="_job_date", DbType="DateTime NOT NULL")]
		public System.DateTime job_date
		{
			get
			{
				return this._job_date;
			}
			set
			{
				if ((this._job_date != value))
				{
					this.Onjob_dateChanging(value);
					this.SendPropertyChanging();
					this._job_date = value;
					this.SendPropertyChanged("job_date");
					this.Onjob_dateChanged();
				}
			}
		}
		
		[Column(Storage="_education", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> education
		{
			get
			{
				return this._education;
			}
			set
			{
				if ((this._education != value))
				{
					this.OneducationChanging(value);
					this.SendPropertyChanging();
					this._education = value;
					this.SendPropertyChanged("education");
					this.OneducationChanged();
				}
			}
		}
		
		[Column(Storage="_degree", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> degree
		{
			get
			{
				return this._degree;
			}
			set
			{
				if ((this._degree != value))
				{
					this.OndegreeChanging(value);
					this.SendPropertyChanging();
					this._degree = value;
					this.SendPropertyChanged("degree");
					this.OndegreeChanged();
				}
			}
		}
		
		[Column(Storage="_prof_cert_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prof_cert_id
		{
			get
			{
				return this._prof_cert_id;
			}
			set
			{
				if ((this._prof_cert_id != value))
				{
					this.Onprof_cert_idChanging(value);
					this.SendPropertyChanging();
					this._prof_cert_id = value;
					this.SendPropertyChanged("prof_cert_id");
					this.Onprof_cert_idChanged();
				}
			}
		}
		
		[Column(Storage="_hospital_duty", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> hospital_duty
		{
			get
			{
				return this._hospital_duty;
			}
			set
			{
				if ((this._hospital_duty != value))
				{
					this.Onhospital_dutyChanging(value);
					this.SendPropertyChanging();
					this._hospital_duty = value;
					this.SendPropertyChanged("hospital_duty");
					this.Onhospital_dutyChanged();
				}
			}
		}
		
		[Column(Storage="_photo", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this.OnphotoChanging(value);
					this.SendPropertyChanging();
					this._photo = value;
					this.SendPropertyChanged("photo");
					this.OnphotoChanged();
				}
			}
		}
		
		[Column(Storage="_person_type", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> person_type
		{
			get
			{
				return this._person_type;
			}
			set
			{
				if ((this._person_type != value))
				{
					this.Onperson_typeChanging(value);
					this.SendPropertyChanging();
					this._person_type = value;
					this.SendPropertyChanged("person_type");
					this.Onperson_typeChanged();
				}
			}
		}
		
		[Column(Storage="_remark", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[Column(Storage="_passwd", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string passwd
		{
			get
			{
				return this._passwd;
			}
			set
			{
				if ((this._passwd != value))
				{
					this.OnpasswdChanging(value);
					this.SendPropertyChanging();
					this._passwd = value;
					this.SendPropertyChanged("passwd");
					this.OnpasswdChanged();
				}
			}
		}
		
		[Column(Storage="_Dept_id", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string Dept_id
		{
			get
			{
				return this._Dept_id;
			}
			set
			{
				if ((this._Dept_id != value))
				{
					this.OnDept_idChanging(value);
					this.SendPropertyChanging();
					this._Dept_id = value;
					this.SendPropertyChanged("Dept_id");
					this.OnDept_idChanged();
				}
			}
		}
		
		[Column(Storage="_Update_other_no", DbType="TinyInt NOT NULL")]
		public byte Update_other_no
		{
			get
			{
				return this._Update_other_no;
			}
			set
			{
				if ((this._Update_other_no != value))
				{
					this.OnUpdate_other_noChanging(value);
					this.SendPropertyChanging();
					this._Update_other_no = value;
					this.SendPropertyChanged("Update_other_no");
					this.OnUpdate_other_noChanged();
				}
			}
		}
		
		[Column(Storage="_Transfer_state", DbType="Int NOT NULL")]
		public int Transfer_state
		{
			get
			{
				return this._Transfer_state;
			}
			set
			{
				if ((this._Transfer_state != value))
				{
					this.OnTransfer_stateChanging(value);
					this.SendPropertyChanging();
					this._Transfer_state = value;
					this.SendPropertyChanged("Transfer_state");
					this.OnTransfer_stateChanged();
				}
			}
		}
		
		[Column(Storage="_add_time", DbType="DateTime NOT NULL")]
		public System.DateTime add_time
		{
			get
			{
				return this._add_time;
			}
			set
			{
				if ((this._add_time != value))
				{
					this.Onadd_timeChanging(value);
					this.SendPropertyChanging();
					this._add_time = value;
					this.SendPropertyChanged("add_time");
					this.Onadd_timeChanged();
				}
			}
		}
		
		[Column(Storage="_BatchGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> BatchGuid
		{
			get
			{
				return this._BatchGuid;
			}
			set
			{
				if ((this._BatchGuid != value))
				{
					this.OnBatchGuidChanging(value);
					this.SendPropertyChanging();
					this._BatchGuid = value;
					this.SendPropertyChanged("BatchGuid");
					this.OnBatchGuidChanged();
				}
			}
		}
		
		[Column(Storage="_is_create_card", DbType="Bit")]
		public System.Nullable<bool> is_create_card
		{
			get
			{
				return this._is_create_card;
			}
			set
			{
				if ((this._is_create_card != value))
				{
					this.Onis_create_cardChanging(value);
					this.SendPropertyChanging();
					this._is_create_card = value;
					this.SendPropertyChanged("is_create_card");
					this.Onis_create_cardChanged();
				}
			}
		}
		
		[Column(Storage="_is_charges", DbType="Bit")]
		public System.Nullable<bool> is_charges
		{
			get
			{
				return this._is_charges;
			}
			set
			{
				if ((this._is_charges != value))
				{
					this.Onis_chargesChanging(value);
					this.SendPropertyChanging();
					this._is_charges = value;
					this.SendPropertyChanged("is_charges");
					this.Onis_chargesChanged();
				}
			}
		}
		
		[Column(Storage="_internals", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string internals
		{
			get
			{
				return this._internals;
			}
			set
			{
				if ((this._internals != value))
				{
					this.OninternalsChanging(value);
					this.SendPropertyChanging();
					this._internals = value;
					this.SendPropertyChanged("internals");
					this.OninternalsChanged();
				}
			}
		}
		
		[Column(Storage="_update_time", DbType="DateTime NOT NULL")]
		public System.DateTime update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

    [Table(Name = "kjpt_common.dbo.com_unit")]
	public partial class com_unit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _unit_id;
		
		private string _unit_name;
		
		private string _gov_passwd;
		
		private string _short_name;
		
		private string _address;
		
		private string _contact;
		
		private string _telephone;
		
		private string _postcode;
		
		private string _parent_unit;
		
		private System.Nullable<System.Guid> _hospital_level;
		
		private byte _cme_score_check_mode;
		
		private System.Guid _cme_standard_kind_id;
		
		private string _Proj_control_top_unit;
		
		private string _attendance_grantscore_top_unit;
		
		private byte _cme_score_avail_state;
		
		private byte _cme_score_check_state;
		
		private int _tmp_oper_people_id;
		
		private string _photo_address;
		
		private int _privilege;
		
		private int _list_order;
		
		private int _open_dept;
		
		private System.DateTime _add_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onunit_idChanging(string value);
    partial void Onunit_idChanged();
    partial void Onunit_nameChanging(string value);
    partial void Onunit_nameChanged();
    partial void Ongov_passwdChanging(string value);
    partial void Ongov_passwdChanged();
    partial void Onshort_nameChanging(string value);
    partial void Onshort_nameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncontactChanging(string value);
    partial void OncontactChanged();
    partial void OntelephoneChanging(string value);
    partial void OntelephoneChanged();
    partial void OnpostcodeChanging(string value);
    partial void OnpostcodeChanged();
    partial void Onparent_unitChanging(string value);
    partial void Onparent_unitChanged();
    partial void Onhospital_levelChanging(System.Nullable<System.Guid> value);
    partial void Onhospital_levelChanged();
    partial void Oncme_score_check_modeChanging(byte value);
    partial void Oncme_score_check_modeChanged();
    partial void Oncme_standard_kind_idChanging(System.Guid value);
    partial void Oncme_standard_kind_idChanged();
    partial void OnProj_control_top_unitChanging(string value);
    partial void OnProj_control_top_unitChanged();
    partial void Onattendance_grantscore_top_unitChanging(string value);
    partial void Onattendance_grantscore_top_unitChanged();
    partial void Oncme_score_avail_stateChanging(byte value);
    partial void Oncme_score_avail_stateChanged();
    partial void Oncme_score_check_stateChanging(byte value);
    partial void Oncme_score_check_stateChanged();
    partial void Ontmp_oper_people_idChanging(int value);
    partial void Ontmp_oper_people_idChanged();
    partial void Onphoto_addressChanging(string value);
    partial void Onphoto_addressChanged();
    partial void OnprivilegeChanging(int value);
    partial void OnprivilegeChanged();
    partial void Onlist_orderChanging(int value);
    partial void Onlist_orderChanged();
    partial void Onopen_deptChanging(int value);
    partial void Onopen_deptChanged();
    partial void Onadd_timeChanging(System.DateTime value);
    partial void Onadd_timeChanged();
    #endregion
		
		public com_unit()
		{
			OnCreated();
		}
		
		[Column(Storage="_unit_id", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string unit_id
		{
			get
			{
				return this._unit_id;
			}
			set
			{
				if ((this._unit_id != value))
				{
					this.Onunit_idChanging(value);
					this.SendPropertyChanging();
					this._unit_id = value;
					this.SendPropertyChanged("unit_id");
					this.Onunit_idChanged();
				}
			}
		}
		
		[Column(Storage="_unit_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string unit_name
		{
			get
			{
				return this._unit_name;
			}
			set
			{
				if ((this._unit_name != value))
				{
					this.Onunit_nameChanging(value);
					this.SendPropertyChanging();
					this._unit_name = value;
					this.SendPropertyChanged("unit_name");
					this.Onunit_nameChanged();
				}
			}
		}
		
		[Column(Storage="_gov_passwd", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string gov_passwd
		{
			get
			{
				return this._gov_passwd;
			}
			set
			{
				if ((this._gov_passwd != value))
				{
					this.Ongov_passwdChanging(value);
					this.SendPropertyChanging();
					this._gov_passwd = value;
					this.SendPropertyChanged("gov_passwd");
					this.Ongov_passwdChanged();
				}
			}
		}
		
		[Column(Storage="_short_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string short_name
		{
			get
			{
				return this._short_name;
			}
			set
			{
				if ((this._short_name != value))
				{
					this.Onshort_nameChanging(value);
					this.SendPropertyChanging();
					this._short_name = value;
					this.SendPropertyChanged("short_name");
					this.Onshort_nameChanged();
				}
			}
		}
		
		[Column(Storage="_address", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[Column(Storage="_contact", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string contact
		{
			get
			{
				return this._contact;
			}
			set
			{
				if ((this._contact != value))
				{
					this.OncontactChanging(value);
					this.SendPropertyChanging();
					this._contact = value;
					this.SendPropertyChanged("contact");
					this.OncontactChanged();
				}
			}
		}
		
		[Column(Storage="_telephone", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string telephone
		{
			get
			{
				return this._telephone;
			}
			set
			{
				if ((this._telephone != value))
				{
					this.OntelephoneChanging(value);
					this.SendPropertyChanging();
					this._telephone = value;
					this.SendPropertyChanged("telephone");
					this.OntelephoneChanged();
				}
			}
		}
		
		[Column(Storage="_postcode", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string postcode
		{
			get
			{
				return this._postcode;
			}
			set
			{
				if ((this._postcode != value))
				{
					this.OnpostcodeChanging(value);
					this.SendPropertyChanging();
					this._postcode = value;
					this.SendPropertyChanged("postcode");
					this.OnpostcodeChanged();
				}
			}
		}
		
		[Column(Storage="_parent_unit", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string parent_unit
		{
			get
			{
				return this._parent_unit;
			}
			set
			{
				if ((this._parent_unit != value))
				{
					this.Onparent_unitChanging(value);
					this.SendPropertyChanging();
					this._parent_unit = value;
					this.SendPropertyChanged("parent_unit");
					this.Onparent_unitChanged();
				}
			}
		}
		
		[Column(Storage="_hospital_level", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> hospital_level
		{
			get
			{
				return this._hospital_level;
			}
			set
			{
				if ((this._hospital_level != value))
				{
					this.Onhospital_levelChanging(value);
					this.SendPropertyChanging();
					this._hospital_level = value;
					this.SendPropertyChanged("hospital_level");
					this.Onhospital_levelChanged();
				}
			}
		}
		
		[Column(Storage="_cme_score_check_mode", DbType="TinyInt NOT NULL")]
		public byte cme_score_check_mode
		{
			get
			{
				return this._cme_score_check_mode;
			}
			set
			{
				if ((this._cme_score_check_mode != value))
				{
					this.Oncme_score_check_modeChanging(value);
					this.SendPropertyChanging();
					this._cme_score_check_mode = value;
					this.SendPropertyChanged("cme_score_check_mode");
					this.Oncme_score_check_modeChanged();
				}
			}
		}
		
		[Column(Storage="_cme_standard_kind_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid cme_standard_kind_id
		{
			get
			{
				return this._cme_standard_kind_id;
			}
			set
			{
				if ((this._cme_standard_kind_id != value))
				{
					this.Oncme_standard_kind_idChanging(value);
					this.SendPropertyChanging();
					this._cme_standard_kind_id = value;
					this.SendPropertyChanged("cme_standard_kind_id");
					this.Oncme_standard_kind_idChanged();
				}
			}
		}
		
		[Column(Storage="_Proj_control_top_unit", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string Proj_control_top_unit
		{
			get
			{
				return this._Proj_control_top_unit;
			}
			set
			{
				if ((this._Proj_control_top_unit != value))
				{
					this.OnProj_control_top_unitChanging(value);
					this.SendPropertyChanging();
					this._Proj_control_top_unit = value;
					this.SendPropertyChanged("Proj_control_top_unit");
					this.OnProj_control_top_unitChanged();
				}
			}
		}
		
		[Column(Storage="_attendance_grantscore_top_unit", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string attendance_grantscore_top_unit
		{
			get
			{
				return this._attendance_grantscore_top_unit;
			}
			set
			{
				if ((this._attendance_grantscore_top_unit != value))
				{
					this.Onattendance_grantscore_top_unitChanging(value);
					this.SendPropertyChanging();
					this._attendance_grantscore_top_unit = value;
					this.SendPropertyChanged("attendance_grantscore_top_unit");
					this.Onattendance_grantscore_top_unitChanged();
				}
			}
		}
		
		[Column(Storage="_cme_score_avail_state", DbType="TinyInt NOT NULL")]
		public byte cme_score_avail_state
		{
			get
			{
				return this._cme_score_avail_state;
			}
			set
			{
				if ((this._cme_score_avail_state != value))
				{
					this.Oncme_score_avail_stateChanging(value);
					this.SendPropertyChanging();
					this._cme_score_avail_state = value;
					this.SendPropertyChanged("cme_score_avail_state");
					this.Oncme_score_avail_stateChanged();
				}
			}
		}
		
		[Column(Storage="_cme_score_check_state", DbType="TinyInt NOT NULL")]
		public byte cme_score_check_state
		{
			get
			{
				return this._cme_score_check_state;
			}
			set
			{
				if ((this._cme_score_check_state != value))
				{
					this.Oncme_score_check_stateChanging(value);
					this.SendPropertyChanging();
					this._cme_score_check_state = value;
					this.SendPropertyChanged("cme_score_check_state");
					this.Oncme_score_check_stateChanged();
				}
			}
		}
		
		[Column(Storage="_tmp_oper_people_id", DbType="Int NOT NULL")]
		public int tmp_oper_people_id
		{
			get
			{
				return this._tmp_oper_people_id;
			}
			set
			{
				if ((this._tmp_oper_people_id != value))
				{
					this.Ontmp_oper_people_idChanging(value);
					this.SendPropertyChanging();
					this._tmp_oper_people_id = value;
					this.SendPropertyChanged("tmp_oper_people_id");
					this.Ontmp_oper_people_idChanged();
				}
			}
		}
		
		[Column(Storage="_photo_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string photo_address
		{
			get
			{
				return this._photo_address;
			}
			set
			{
				if ((this._photo_address != value))
				{
					this.Onphoto_addressChanging(value);
					this.SendPropertyChanging();
					this._photo_address = value;
					this.SendPropertyChanged("photo_address");
					this.Onphoto_addressChanged();
				}
			}
		}
		
		[Column(Storage="_privilege", DbType="Int NOT NULL")]
		public int privilege
		{
			get
			{
				return this._privilege;
			}
			set
			{
				if ((this._privilege != value))
				{
					this.OnprivilegeChanging(value);
					this.SendPropertyChanging();
					this._privilege = value;
					this.SendPropertyChanged("privilege");
					this.OnprivilegeChanged();
				}
			}
		}
		
		[Column(Storage="_list_order", DbType="Int NOT NULL")]
		public int list_order
		{
			get
			{
				return this._list_order;
			}
			set
			{
				if ((this._list_order != value))
				{
					this.Onlist_orderChanging(value);
					this.SendPropertyChanging();
					this._list_order = value;
					this.SendPropertyChanged("list_order");
					this.Onlist_orderChanged();
				}
			}
		}
		
		[Column(Storage="_open_dept", DbType="Int NOT NULL")]
		public int open_dept
		{
			get
			{
				return this._open_dept;
			}
			set
			{
				if ((this._open_dept != value))
				{
					this.Onopen_deptChanging(value);
					this.SendPropertyChanging();
					this._open_dept = value;
					this.SendPropertyChanged("open_dept");
					this.Onopen_deptChanged();
				}
			}
		}
		
		[Column(Storage="_add_time", DbType="DateTime NOT NULL")]
		public System.DateTime add_time
		{
			get
			{
				return this._add_time;
			}
			set
			{
				if ((this._add_time != value))
				{
					this.Onadd_timeChanging(value);
					this.SendPropertyChanging();
					this._add_time = value;
					this.SendPropertyChanged("add_time");
					this.Onadd_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

    [Table(Name = "kjpt_cme.dbo.cme_person")]
	public partial class cme_person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _cme_person_id;
		
		private System.Guid _com_person_id;
		
		private string _cme_year;
		
		private System.Guid _title_id;
		
		private System.Guid _person_state_id;
		
		private string _unit;
		
		private System.Nullable<System.Guid> _hospital_level;
		
		private string _remark;
		
		private System.DateTime _add_time;
		
		private int _key_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncme_person_idChanging(System.Guid value);
    partial void Oncme_person_idChanged();
    partial void Oncom_person_idChanging(System.Guid value);
    partial void Oncom_person_idChanged();
    partial void Oncme_yearChanging(string value);
    partial void Oncme_yearChanged();
    partial void Ontitle_idChanging(System.Guid value);
    partial void Ontitle_idChanged();
    partial void Onperson_state_idChanging(System.Guid value);
    partial void Onperson_state_idChanged();
    partial void OnunitChanging(string value);
    partial void OnunitChanged();
    partial void Onhospital_levelChanging(System.Nullable<System.Guid> value);
    partial void Onhospital_levelChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void Onadd_timeChanging(System.DateTime value);
    partial void Onadd_timeChanged();
    partial void Onkey_idChanging(int value);
    partial void Onkey_idChanged();
    #endregion
		
		public cme_person()
		{
			OnCreated();
		}
		
		[Column(Storage="_cme_person_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid cme_person_id
		{
			get
			{
				return this._cme_person_id;
			}
			set
			{
				if ((this._cme_person_id != value))
				{
					this.Oncme_person_idChanging(value);
					this.SendPropertyChanging();
					this._cme_person_id = value;
					this.SendPropertyChanged("cme_person_id");
					this.Oncme_person_idChanged();
				}
			}
		}
		
		[Column(Storage="_com_person_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid com_person_id
		{
			get
			{
				return this._com_person_id;
			}
			set
			{
				if ((this._com_person_id != value))
				{
					this.Oncom_person_idChanging(value);
					this.SendPropertyChanging();
					this._com_person_id = value;
					this.SendPropertyChanged("com_person_id");
					this.Oncom_person_idChanged();
				}
			}
		}
		
		[Column(Storage="_cme_year", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string cme_year
		{
			get
			{
				return this._cme_year;
			}
			set
			{
				if ((this._cme_year != value))
				{
					this.Oncme_yearChanging(value);
					this.SendPropertyChanging();
					this._cme_year = value;
					this.SendPropertyChanged("cme_year");
					this.Oncme_yearChanged();
				}
			}
		}
		
		[Column(Storage="_title_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid title_id
		{
			get
			{
				return this._title_id;
			}
			set
			{
				if ((this._title_id != value))
				{
					this.Ontitle_idChanging(value);
					this.SendPropertyChanging();
					this._title_id = value;
					this.SendPropertyChanged("title_id");
					this.Ontitle_idChanged();
				}
			}
		}
		
		[Column(Storage="_person_state_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid person_state_id
		{
			get
			{
				return this._person_state_id;
			}
			set
			{
				if ((this._person_state_id != value))
				{
					this.Onperson_state_idChanging(value);
					this.SendPropertyChanging();
					this._person_state_id = value;
					this.SendPropertyChanged("person_state_id");
					this.Onperson_state_idChanged();
				}
			}
		}
		
		[Column(Storage="_unit", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				if ((this._unit != value))
				{
					this.OnunitChanging(value);
					this.SendPropertyChanging();
					this._unit = value;
					this.SendPropertyChanged("unit");
					this.OnunitChanged();
				}
			}
		}
		
		[Column(Storage="_hospital_level", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> hospital_level
		{
			get
			{
				return this._hospital_level;
			}
			set
			{
				if ((this._hospital_level != value))
				{
					this.Onhospital_levelChanging(value);
					this.SendPropertyChanging();
					this._hospital_level = value;
					this.SendPropertyChanged("hospital_level");
					this.Onhospital_levelChanged();
				}
			}
		}
		
		[Column(Storage="_remark", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[Column(Storage="_add_time", DbType="DateTime NOT NULL")]
		public System.DateTime add_time
		{
			get
			{
				return this._add_time;
			}
			set
			{
				if ((this._add_time != value))
				{
					this.Onadd_timeChanging(value);
					this.SendPropertyChanging();
					this._add_time = value;
					this.SendPropertyChanged("add_time");
					this.Onadd_timeChanged();
				}
			}
		}
		
		[Column(Storage="_key_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int key_id
		{
			get
			{
				return this._key_id;
			}
			set
			{
				if ((this._key_id != value))
				{
					this.Onkey_idChanging(value);
					this.SendPropertyChanging();
					this._key_id = value;
					this.SendPropertyChanged("key_id");
					this.Onkey_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

    [Table(Name = "kjpt_cme.dbo.cme_year")]
	public partial class cme_year : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _cme_year_id;
		
		private System.Guid _cme_standard_kind_id;
		
		private string _cme_year1;
		
		private System.DateTime _start_date;
		
		private System.DateTime _end_date;
		
		private System.DateTime _add_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncme_year_idChanging(System.Guid value);
    partial void Oncme_year_idChanged();
    partial void Oncme_standard_kind_idChanging(System.Guid value);
    partial void Oncme_standard_kind_idChanged();
    partial void Oncme_year1Changing(string value);
    partial void Oncme_year1Changed();
    partial void Onstart_dateChanging(System.DateTime value);
    partial void Onstart_dateChanged();
    partial void Onend_dateChanging(System.DateTime value);
    partial void Onend_dateChanged();
    partial void Onadd_timeChanging(System.DateTime value);
    partial void Onadd_timeChanged();
    #endregion
		
		public cme_year()
		{
			OnCreated();
		}
		
		[Column(Storage="_cme_year_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid cme_year_id
		{
			get
			{
				return this._cme_year_id;
			}
			set
			{
				if ((this._cme_year_id != value))
				{
					this.Oncme_year_idChanging(value);
					this.SendPropertyChanging();
					this._cme_year_id = value;
					this.SendPropertyChanged("cme_year_id");
					this.Oncme_year_idChanged();
				}
			}
		}
		
		[Column(Storage="_cme_standard_kind_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid cme_standard_kind_id
		{
			get
			{
				return this._cme_standard_kind_id;
			}
			set
			{
				if ((this._cme_standard_kind_id != value))
				{
					this.Oncme_standard_kind_idChanging(value);
					this.SendPropertyChanging();
					this._cme_standard_kind_id = value;
					this.SendPropertyChanged("cme_standard_kind_id");
					this.Oncme_standard_kind_idChanged();
				}
			}
		}
		
		[Column(Name="cme_year", Storage="_cme_year1", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string cme_year1
		{
			get
			{
				return this._cme_year1;
			}
			set
			{
				if ((this._cme_year1 != value))
				{
					this.Oncme_year1Changing(value);
					this.SendPropertyChanging();
					this._cme_year1 = value;
					this.SendPropertyChanged("cme_year1");
					this.Oncme_year1Changed();
				}
			}
		}
		
		[Column(Storage="_start_date", DbType="DateTime NOT NULL")]
		public System.DateTime start_date
		{
			get
			{
				return this._start_date;
			}
			set
			{
				if ((this._start_date != value))
				{
					this.Onstart_dateChanging(value);
					this.SendPropertyChanging();
					this._start_date = value;
					this.SendPropertyChanged("start_date");
					this.Onstart_dateChanged();
				}
			}
		}
		
		[Column(Storage="_end_date", DbType="DateTime NOT NULL")]
		public System.DateTime end_date
		{
			get
			{
				return this._end_date;
			}
			set
			{
				if ((this._end_date != value))
				{
					this.Onend_dateChanging(value);
					this.SendPropertyChanging();
					this._end_date = value;
					this.SendPropertyChanged("end_date");
					this.Onend_dateChanged();
				}
			}
		}
		
		[Column(Storage="_add_time", DbType="DateTime NOT NULL")]
		public System.DateTime add_time
		{
			get
			{
				return this._add_time;
			}
			set
			{
				if ((this._add_time != value))
				{
					this.Onadd_timeChanging(value);
					this.SendPropertyChanging();
					this._add_time = value;
					this.SendPropertyChanged("add_time");
					this.Onadd_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

    [Table(Name = "kjpt_cme.dbo.cme_unit_level")]
	public partial class cme_unit_level : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _unit_level_id;
		
		private string _unit_level_name;
		
		private System.Guid _cme_standard_kind_id;
		
		private int _list_order;
		
		private System.DateTime _add_time;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onunit_level_idChanging(System.Guid value);
    partial void Onunit_level_idChanged();
    partial void Onunit_level_nameChanging(string value);
    partial void Onunit_level_nameChanged();
    partial void Oncme_standard_kind_idChanging(System.Guid value);
    partial void Oncme_standard_kind_idChanged();
    partial void Onlist_orderChanging(int value);
    partial void Onlist_orderChanged();
    partial void Onadd_timeChanging(System.DateTime value);
    partial void Onadd_timeChanged();
    #endregion
		
		public cme_unit_level()
		{
			OnCreated();
		}
		
		[Column(Storage="_unit_level_id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid unit_level_id
		{
			get
			{
				return this._unit_level_id;
			}
			set
			{
				if ((this._unit_level_id != value))
				{
					this.Onunit_level_idChanging(value);
					this.SendPropertyChanging();
					this._unit_level_id = value;
					this.SendPropertyChanged("unit_level_id");
					this.Onunit_level_idChanged();
				}
			}
		}
		
		[Column(Storage="_unit_level_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string unit_level_name
		{
			get
			{
				return this._unit_level_name;
			}
			set
			{
				if ((this._unit_level_name != value))
				{
					this.Onunit_level_nameChanging(value);
					this.SendPropertyChanging();
					this._unit_level_name = value;
					this.SendPropertyChanged("unit_level_name");
					this.Onunit_level_nameChanged();
				}
			}
		}
		
		[Column(Storage="_cme_standard_kind_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid cme_standard_kind_id
		{
			get
			{
				return this._cme_standard_kind_id;
			}
			set
			{
				if ((this._cme_standard_kind_id != value))
				{
					this.Oncme_standard_kind_idChanging(value);
					this.SendPropertyChanging();
					this._cme_standard_kind_id = value;
					this.SendPropertyChanged("cme_standard_kind_id");
					this.Oncme_standard_kind_idChanged();
				}
			}
		}
		
		[Column(Storage="_list_order", DbType="Int NOT NULL")]
		public int list_order
		{
			get
			{
				return this._list_order;
			}
			set
			{
				if ((this._list_order != value))
				{
					this.Onlist_orderChanging(value);
					this.SendPropertyChanging();
					this._list_order = value;
					this.SendPropertyChanged("list_order");
					this.Onlist_orderChanged();
				}
			}
		}
		
		[Column(Storage="_add_time", DbType="DateTime NOT NULL")]
		public System.DateTime add_time
		{
			get
			{
				return this._add_time;
			}
			set
			{
				if ((this._add_time != value))
				{
					this.Onadd_timeChanging(value);
					this.SendPropertyChanging();
					this._add_time = value;
					this.SendPropertyChanged("add_time");
					this.Onadd_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
