<?xml version="1.0" encoding="utf-8"?>
<Database Name="SilverMoon" Class="SMDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.sm_biz_Workpiece" Member="sm_biz_Workpieces">
    <Type Name="sm_biz_Workpiece">
      <Column Name="MachineID" Type="System.Char" DbType="NChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Char" DbType="NChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Shift" Type="System.Char" DbType="NChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Serial" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="sm_biz_State_sm_biz_Workpiece" Member="sm_biz_State" ThisKey="State" OtherKey="ID" Type="sm_biz_State" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sm_biz_State" Member="sm_biz_States">
    <Type Name="sm_biz_State">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Group]" Member="Group" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="sm_biz_State_sm_biz_Workpiece" Member="sm_biz_Workpieces" ThisKey="ID" OtherKey="State" Type="sm_biz_Workpiece" />
    </Type>
  </Table>
</Database>