application: lusionx
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: home.py

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /proxy.*
  script: proxy.py

- url: /msg
  script: msg.py

- url: /msg/\w*
  script: msg.py

- url: /.*
  script: not_found.py
