application: lusionx
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: home.py

- url: /static
  static_dir: static

- url: /learn.*
  script: learn.py

- url: /test.*
  script: test.py

- url: /msg.*
  script: msg.py

- url: /.*
  script: not_found.py
