application: fucrkl
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /ckeditor/.*
  script: $PYTHON_LIB/google/appengine/ext/zipserve

- url: /.*
  script: main.py
