application: lusionx
version: 1
runtime: python
api_version: 1

#1.notice:the *.py must can handler the url
#2.every url must start with '/' and  can't end with '/'
#3.every url must match completely
handlers:

- url: /
  script: home.py

- url: /p/.*
  script: post.py

- url: /admin
  script: admin/home.py
  login: admin

- url: /admin/post/.*
  script: admin/post.py
  login: admin

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /static
  static_dir: static

- url: /ckeditor/.*
  script: ckeditor.py

- url: /.*
  script: not_found.py
