application: lusionx
version: 1
runtime: python
api_version: 1

#notice:the *.py must can handler the url 
handlers:
#- url: /home\.html
#  script: home.py

- url: /
  script: index.py  

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /proxy/.*|/proxy
  script: proxy.py

- url: /msg/.*|/msg
  script: msg.py
  
- url: /.*
  script: not_found.py
