<?xml version="1.0" encoding="utf-8"?><Database Name="ManufactureTest" Class="ManufactureTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=ManufactureTest;Persist Security Info=True;User ID=sa" SettingsObjectName="Alxf.ProduceCard.DAL.Properties.Settings" SettingsPropertyName="ManufactureTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Card_Producer" Member="Card_Producers">
    <Type Name="Card_Producer">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WorkSerial" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="CompleteTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="OrderSerial" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="ProduceTotal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalFree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalFee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[File]" Member="Files">
    <Type Name="File">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="ContentLength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Context" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserInf" Member="UserInfs">
    <Type Name="UserInf">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Area" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="RealName" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="ReceivingPerson" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="ReceivingUnit" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="ReceivingAddress" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(521) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Card_Apply" Member="Card_Applies">
    <Type Name="Card_Apply">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderSerial" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="ProduceQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZhuLiName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="OriginalData" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ConfirmQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HandledData" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="HandledQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProducerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StorageSerial" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Card_ApplyState" Member="Card_ApplyStates">
    <Type Name="Card_ApplyState">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplyID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="HandlerUser" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChangeTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsCurrent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>