<?xml version="1.0" encoding="utf-8"?><Database Name="AlxfDemo" Class="ADBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=AlxfDemo;Persist Security Info=True;User ID=sa" SettingsObjectName="Alxf.DAL.Demo.Properties.Settings" SettingsPropertyName="AlxfDemoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VideoComment" Member="VideoComments">
    <Type Name="VideoComment">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CartonID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AddTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="VideoObj_VideoComment" Member="VideoObj" ThisKey="CartonID" OtherKey="ID" Type="VideoObj" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VideoType" Member="VideoTypes">
    <Type Name="VideoType">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="VideoType_VideoObj" Member="VideoObjs" ThisKey="ID" OtherKey="TypeID" Type="VideoObj" />
    </Type>
  </Table>
  <Table Name="dbo.VideoObj" Member="VideoObjs">
    <Type Name="VideoObj">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name_cn" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Name_en" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Episodes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DownLink" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="VideoObj_VideoComment" Member="VideoComments" ThisKey="ID" OtherKey="CartonID" Type="VideoComment" />
      <Association Name="VideoType_VideoObj" Member="VideoType" ThisKey="TypeID" OtherKey="ID" Type="VideoType" IsForeignKey="true" />
    </Type>
  </Table>
</Database>